import Head from 'next/head'
import Image from 'next/image'
import Footer from '../Components/footer'
import Navbar from '../Components/navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar/>
    <div>
    <img src="/shop for style-logos.jpeg" alt="" />
    </div>

    <Footer></Footer>
    </div>
  )
}
